# Generated by Django 2.2.7 on 2019-11-10 06:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='category_tag',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 11, 10, 6, 33, 48, 813549, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='eventName',
            field=models.CharField(default='event', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='group',
            field=models.CharField(default='group', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(default='location', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='poster',
            field=models.ImageField(default='default_poster.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='time_end',
            field=models.TimeField(default='3:00'),
        ),
        migrations.AddField(
            model_name='post',
            name='time_start',
            field=models.TimeField(default='10:00'),
        ),
    ]
