# Generated by Django 2.2.7 on 2019-11-10 07:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0003_auto_20191110_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category_tag',
            field=models.CharField(default='Insert Type of Event i.e. Food or Sports Here', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(default='Insert Location on Campus Here', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='time_end',
            field=models.TimeField(default='3:00'),
        ),
        migrations.AddField(
            model_name='post',
            name='time_start',
            field=models.TimeField(default='10:00'),
        ),
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.CharField(default='Insert Student Group Here', max_length=50),
        ),
    ]
