# Generated by Django 2.2.7 on 2019-11-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0004_auto_20191110_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(default='name@ualberta.ca', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='category_tag',
            field=models.CharField(default='Select Type: Food Sale, Social Event, Presentation, Activity', max_length=50),
        ),
    ]
